  # Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


commands:
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y
jobs:  
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |  #deploy = create + update 
            echo ${CIRCLE_WORKFLOW_ID:0:5}
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1          
  
  configure_infrastructure: 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c8:56:17:ac:e8:f1:0e:f4:c7:26:0b:86:1b:58:10:14"] # You can get this ID in the section where you registered the SSH Key
      - install_ansible
      - run :
          name: Install AWS-CLI and 
          command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version #verify aws cli installation
      - run : 
          name : Get Node-exporter IP 
          command : |
                aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> /home/circleci/project/inventory
                cat inventory

      - run:
          name: Configure Prometheus Node exporter 
          command: |
            pwd
            ls
            ansible-playbook -i /home/circleci/project/inventory main-remote.yml


workflows:
  Prometheus:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires : [configure_infrastructure]