- name: Download and unpack node exporter binary to /usr/local/bin
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    owner: "root"
    group: "root" 

- name : Copy node-exporter service file 
  copy:
    src: "files/node_exporter.service"
    dest: "/etc/systemd/system/"
    owner: root
    group: root        

- name: Make sure 'node_exporter' service is started and enabled
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes


- name: Do permit traffic in default zone for 'node_exporter' on port 9001/tcp
  firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled